// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations.PostgreSQL
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240525090529_PriceRulesAndConditions")]
    partial class PriceRulesAndConditions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Exchanges.Exchange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_exchanges");

                    b.ToTable("exchanges", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Instruments.Instrument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("base_asset");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<long>("ExchangeId")
                        .HasColumnType("bigint")
                        .HasColumnName("exchange_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("quote_asset");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("ExchangeId")
                        .HasDatabaseName("ix_instruments_exchange_id");

                    b.ToTable("instruments", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Instruments.InstrumentPrice", b =>
                {
                    b.Property<long>("ExchangeId")
                        .HasColumnType("bigint")
                        .HasColumnName("exchange_id");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("volume");

                    b.HasIndex("ExchangeId")
                        .HasDatabaseName("ix_instrument_prices_exchange_id");

                    b.ToTable("instrument_prices", (string)null);
                });

            modelBuilder.Entity("Domain.Models.PriceRule.PriceCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_value");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("condition_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long>("RuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("rule_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_price_conditions");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_price_conditions_rule_id");

                    b.ToTable("price_conditions", (string)null);
                });

            modelBuilder.Entity("Domain.Models.PriceRule.PriceRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_price_rules");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_price_rules_instrument_id");

                    b.ToTable("price_rules", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Models.FifteenMinCandle", b =>
                {
                    b.Property<DateTimeOffset>("Bucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<long>("ExchangeId")
                        .HasColumnType("bigint")
                        .HasColumnName("exchange_id");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("volume");

                    b.HasIndex("ExchangeId")
                        .HasDatabaseName("ix_fifteen_min_candle_exchange_id");

                    b.ToTable((string)null);

                    b.ToView("fifteen_min_candle", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Models.FiveMinCandle", b =>
                {
                    b.Property<DateTimeOffset>("Bucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<long>("ExchangeId")
                        .HasColumnType("bigint")
                        .HasColumnName("exchange_id");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("volume");

                    b.HasIndex("ExchangeId")
                        .HasDatabaseName("ix_five_min_candle_exchange_id");

                    b.ToTable((string)null);

                    b.ToView("five_min_candle", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Models.OneHourCandle", b =>
                {
                    b.Property<DateTimeOffset>("Bucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<long>("ExchangeId")
                        .HasColumnType("bigint")
                        .HasColumnName("exchange_id");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("volume");

                    b.HasIndex("ExchangeId")
                        .HasDatabaseName("ix_one_hour_candle_exchange_id");

                    b.ToTable((string)null);

                    b.ToView("one_hour_candle", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Models.OneMinCandle", b =>
                {
                    b.Property<DateTimeOffset>("Bucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<long>("ExchangeId")
                        .HasColumnType("bigint")
                        .HasColumnName("exchange_id");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("volume");

                    b.HasIndex("ExchangeId")
                        .HasDatabaseName("ix_one_min_candle_exchange_id");

                    b.ToTable((string)null);

                    b.ToView("one_min_candle", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Models.TenMinCandle", b =>
                {
                    b.Property<DateTimeOffset>("Bucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<long>("ExchangeId")
                        .HasColumnType("bigint")
                        .HasColumnName("exchange_id");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("volume");

                    b.HasIndex("ExchangeId")
                        .HasDatabaseName("ix_ten_min_candle_exchange_id");

                    b.ToTable((string)null);

                    b.ToView("ten_min_candle", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Instruments.Instrument", b =>
                {
                    b.HasOne("Domain.Models.Exchanges.Exchange", "Exchange")
                        .WithMany("Instruments")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instruments_exchanges_exchange_id");

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("Domain.Models.Instruments.InstrumentPrice", b =>
                {
                    b.HasOne("Domain.Models.Exchanges.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instrument_prices_exchanges_exchange_id");

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("Domain.Models.PriceRule.PriceCondition", b =>
                {
                    b.HasOne("Domain.Models.PriceRule.PriceRule", "Rule")
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_conditions_price_rules_rule_id");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Domain.Models.PriceRule.PriceRule", b =>
                {
                    b.HasOne("Domain.Models.Instruments.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_rules_instruments_instrument_id");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("Infrastructure.Data.Models.FifteenMinCandle", b =>
                {
                    b.HasOne("Domain.Models.Exchanges.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fifteen_min_candle_exchanges_exchange_id");

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("Infrastructure.Data.Models.FiveMinCandle", b =>
                {
                    b.HasOne("Domain.Models.Exchanges.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_five_min_candle_exchanges_exchange_id");

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("Infrastructure.Data.Models.OneHourCandle", b =>
                {
                    b.HasOne("Domain.Models.Exchanges.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_one_hour_candle_exchanges_exchange_id");

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("Infrastructure.Data.Models.OneMinCandle", b =>
                {
                    b.HasOne("Domain.Models.Exchanges.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_one_min_candle_exchanges_exchange_id");

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("Infrastructure.Data.Models.TenMinCandle", b =>
                {
                    b.HasOne("Domain.Models.Exchanges.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ten_min_candle_exchanges_exchange_id");

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("Domain.Models.Exchanges.Exchange", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("Domain.Models.PriceRule.PriceRule", b =>
                {
                    b.Navigation("Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
